%YAML:1.0
#--------------------------------------------------------------------------------------------
# ConfigName: KITTI_20110930_0033.yaml
# file parameters
#--------------------------------------------------------------------------------------------
## input
InputDirectory: "/home/huanhexiao/Dataset/VIG_FactorGraph/KITTI/2011_09_30_drive_0033_extract/"
IMUfile: "IMU_VehicleXYZ_Inpl.txt"
GNSSfile: "GNSSPos_1s.txt"
CamPath: "image_00/data_PyrDw/"
CamTimefile: "KittiCam00Timestamps.txt"
## output
OutputDirectory: "/home/huanhexiao/WORK/OutPut/VIG_FactorGraph/KITTI/2011_09_30_drive_0033_extract/"      
Navfile: "NavStates.txt"  # navigation states
IMUBiasfile: "IMUErrorStates.txt"   # imu error terms
KMLFilename: "pos.kml"     # kml
FeatureTableFile: "TrackedFeatures.txt" # output feature table of the tracker
CamPoseFile: "CamPose.txt"    # output q s2c and Ts in c,camera calibration parameters
WriteVideo: 1
VideoName: "TrackedFramesVideo.avi"     # output video
NavFrame: ENU


#--------------------------------------------------------------------------------------------
# imu Configuration
#--------------------------------------------------------------------------------------------
UseIMU: 1
IMUType: 8                    # imu type, [0:,1:,2:,3:,4:,5:3dm-gx-3-35,...8:kitti,9:gtsam example], 
IMUMisalignMode: 0            # 0:e-formulation,1:phi,2:psi,3:s0 local frame
                              # it also means the GNSS/INS frame you choose
                              # if images avilable,the frame will transform to s0 frame
IMUFileType: 0                # what kind of imu data, rate or increment
                              ##  rate:      0,   gyro(rad/s),acc(m/s^2),for mems
                              ##  increment: 1,   gyro(rad),acc(m/s),for mems
IMUStartTime: 479531.00510909 # epoch before 479531.00510909
IMUEndTime: 479696.03176795
IMUDt: 0.01                   # sampling interval
# Extrinsic parameter between IMU and body.
# Rotation from body frame to imu frame, identical matrix
Cbody2imu: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [90.25182978,0.84997390,89.55229569]
# Translation from body frame origin point to imu's, in body frame
## i.e.,3dm-gx-3-35 coord in body frame
Timu2body: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [1.1439,-0.3127,0.7265]
## initial set
IMUErrorStates: !!opencv-matrix
  rows: 4
  cols: 3
  dt: d
  data: [0.0,0.0,0.0,        # GyroBias
         0.0,0.0,0.0,        # AccBias
         0.0,0.0,0.0,        # GyroScale
         0.0,0.0,0.0]        # AccScale
## Initial PVA, note this is the GNSS antenna position, not IMU
### velocity of the MEMS chassis or sensor frame in e frame
IniVn:         !!opencv-matrix # initial velocity in n-frame (ENU,m/s)
  rows: 3
  cols: 1
  dt: d
  data: [2.63083245,-1.46457285,0.09127434]  # 479530.99508015
IniRVi2n:       !!opencv-matrix # (°)
  rows: 3
  cols: 1
  dt: d
  data: [2.55762630,-1.85231526,-28.38700335]   # qi2n=att2qua(Ri2n/180*pi), roll pitch, yaw, at 479530.99508015
InitAttSigma:  0.02            # 0.02 deg std for roll and pitch, 2 times 3 deg for yaw std
InitPosSigma:  0.01            # 0.01 m std for position
InitVelSigma:  0.01            # 0.01 m/s std for velocity
InitAccBiasSigma:  0.1            # 
InitGyroBiasSigma:  5.0e-5        # 
InitAccBetwBiasSigma: 0.000167    # 
InitGyroBetwBiasSigma: 2.91e-006  # 
AccSigma:  0.01               # 
GyroSigma:  0.000175          # 
IntgSigma:  1e-8              # 
g:        !!opencv-matrix # (°)
  rows: 3
  cols: 1
  dt: d
  data: [0,0,-9.81]           # gravity, ENU for Nav Coordinate
w_coriolis:       !!opencv-matrix # (°)
  rows: 3
  cols: 1
  dt: d
  data: [0.0,0.0,0.0]         # 


#--------------------------------------------------------------------------------------------
# GNSS Configuration
#--------------------------------------------------------------------------------------------
UseGNSS: 1
UseGNSSStd: 0            # use the std in the rtklib GNSS solutons
Timu2ant:  !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0,0,0]          # [-0.3127,0.7265,-1.1439]
IniBLH_ant: !!opencv-matrix      # [B(°), L(°),H(m)]
  rows: 3
  cols: 1
  dt: d
  data: [48.972098563194000,8.476163215565800,201.92543]   # 479530.99508015
GNSSNum: 40000           # 10Hz x 100, the interval of GNSS coverage
GNSSPosType: 2           # 1 for rinex raw,2 for RTKlib solution
GNSSAttSigma: 0          # 
GNSSPosSigma: 0.03       # 
InitGNSSResidulThreshold: !!opencv-matrix  # [E(m), N(m),U(m)]
  rows: 3
  cols: 1
  dt: d
  data: [10,10,15]
GNSSResidulThresholdFactor: [1.0,5.0]      # k0,k1

#--------------------------------------------------------------------------------------------
# ZUPT Configuration
#--------------------------------------------------------------------------------------------
ZUPTSE:     !!opencv-matrix  # zupt start and end time
  rows: 2
  cols: 1
  dt: d
  data: [414840.0, 415175.0] # zupt start and end time
SigmaZUPT: 0.1           # unit:m/s
RateZUPT: 10             # round(sqrt(1/Configuration.dt))

#--------------------------------------------------------------------------------------------
# NHC Configuration
#--------------------------------------------------------------------------------------------
UseNHC: 1
SigmaNHC: 0.3            # unit m/s
RateNHC: 10              # round(sqrt(1/Configuration.dt)). rateNHC=inf,this generally cause worse results
MinNHCVel: 2.0           # minimum velocity before applying the NHC, this option decouples ZUPT and NHC

#--------------------------------------------------------------------------------------------
# Camera Configuration
#--------------------------------------------------------------------------------------------
UseCam: 1
Cam.fps: 10.0            # Camera frames per second, the window size is  fps+1
WindowSize: 11           # It's useless atcually, configuration.cpp define that mWindowSize= fps+1
Equalize: 0              # Contrast Limited AHE (CLAHE) is a variant of adaptive histogram equalization in which the contrast amplification is limited
FishEye: 1               # using fish eye
FishEyeMask: "./config/KITTI_mask.jpg"
PubFrequency: 10         # image publish frequency
## intrinsic parameters
Cam.nCols: 696
Cam.nRows: 256
Cam.fcx: 489.34885
Cam.fcy: 485.87175
Cam.ccx: 345
Cam.ccy: 124.8611
Cam.alpha: 0.0
### Cam.K: 
### [ Cam.fc(1)   Cam.alpha*Cam.fc(1)   Cam.cc(1)
###          0         Cam.fc(2)        Cam.cc(2)
###          0           0                  1   ]
## distortion parameters
Cam.CamDistCoef: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [-0.37925670,0.21212030,0.00091826,0.00191130,-0.07605535] #k1,k2,p1,p2,k3
Sigma_Pixel: 1.5           # unit pixel
InitPixelResidulThreshold: !!opencv-matrix  # [u(pixel), v(pixel)]
  rows: 2
  cols: 1
  dt: d
  data: [5,5]
PixelResidulThresholdFactor: [1.0,5.0]   # k0,k1
Sigma_TrgPoint3: 5         # triangulated point3 sigma
ImageSeqType: 0            # 0 for image sequence and 1 for video
InitiImageID: 1            # 415530 GTOW
LastImageID: 1600          # at least 5 minutes

#--------------------------------------------------------------------------------------------
# Feature Tracker Configuration
#--------------------------------------------------------------------------------------------
MaxFeatureNumPerFrame: 200 # maximum points in the the currrent image 
MinFeatureNumInStates: 30  # minimum number of tracked points in the features_, i.e.,in the states,
                           # before creating a new key frame of features by triangulation from the feature table
FundamentalThreshold: 1.0  # CV Find Fundamental Matrix Threshold
NumUnDisIter: 8

#--------------------------------------------------------------------------------------------
# Feature Manager Configuration
#--------------------------------------------------------------------------------------------
FocalLength: 460.0         # focal length, directly from VINS, VINS use the value for every camera
                           # it may not be correct for albi
MinKeyFrameParallax: 10.0  # keyframe selection threshold (pixel)
                           # the actuall selection is MinKeyFrameParallax/FocalLength = 10.0/460

#--------------------------------------------------------------------------------------------
# Optimization Solver Configuration
#--------------------------------------------------------------------------------------------
Optimizer: "IncrementalFixedLagSmoother"   # ISAM2, IncrementalFixedLagSmoother supportted now
IsamParams_RelinearizeSkip: 10
NonLinearISAMRelinearizeInterval: 3
SmootherLag: 20.0          # smoother lag (in seconds)
NumFLSmootherUpdIters: 2   # number of smoother update iterations

#--------------------------------------------------------------------------------------------
# Viewer Configuration
#--------------------------------------------------------------------------------------------
UseViewer: 1
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

# Test paras
TestPauseEpoch: 479531.00510909
TestFramesThreshold: 20